/**
 * PowerMeter API
 * API
 *
 * The version of the OpenAPI document: 2021.4.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * InstanceSupply.h
 *
 * 
 */

#ifndef POWERMETER_MODEL_InstanceSupply_H_
#define POWERMETER_MODEL_InstanceSupply_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace powermeter {
namespace model {


/// <summary>
/// 
/// </summary>
class  InstanceSupply
    : public ModelBase
{
public:
    InstanceSupply();
    virtual ~InstanceSupply();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// InstanceSupply members

    /// <summary>
    /// 
    /// </summary>
    int32_t getId() const;
    bool idIsSet() const;
    void unsetId();

    void setId(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getDesignSupply() const;
    bool designSupplyIsSet() const;
    void unsetDesign_supply();

    void setDesignSupply(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getDesignSupplyName() const;
    bool designSupplyNameIsSet() const;
    void unsetDesign_supply_name();

    void setDesignSupplyName(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getMasterSupply() const;
    bool masterSupplyIsSet() const;
    void unsetMaster_supply();

    void setMasterSupply(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getMasterSupplyName() const;
    bool masterSupplyNameIsSet() const;
    void unsetMaster_supply_name();

    void setMasterSupplyName(const utility::string_t& value);


protected:
    int32_t m_Id;
    bool m_IdIsSet;
    int32_t m_Design_supply;
    bool m_Design_supplyIsSet;
    utility::string_t m_Design_supply_name;
    bool m_Design_supply_nameIsSet;
    int32_t m_Master_supply;
    bool m_Master_supplyIsSet;
    utility::string_t m_Master_supply_name;
    bool m_Master_supply_nameIsSet;
};


}
}

#endif /* POWERMETER_MODEL_InstanceSupply_H_ */
