/**
 * PowerMeter API
 * API
 *
 * The version of the OpenAPI document: 2021.4.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "PCB.h"

namespace powermeter {
namespace model {




PCB::PCB()
{
    m_Id = 0;
    m_IdIsSet = false;
    m_Editable = false;
    m_EditableIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
    m_Descr = utility::conversions::to_string_t("");
    m_DescrIsSet = false;
    m_R_convection = 0.0;
    m_R_convectionIsSet = false;
    m_C_convection = 0.0;
    m_C_convectionIsSet = false;
    m_Width = 0.0;
    m_WidthIsSet = false;
    m_Height = 0.0;
    m_HeightIsSet = false;
    m_Thickness = 0.0;
    m_ThicknessIsSet = false;
    m_VersionIsSet = false;
    m_Current_version = 0;
    m_Current_versionIsSet = false;
}

PCB::~PCB()
{
}

void PCB::validate()
{
    // TODO: implement validation
}

web::json::value PCB::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_IdIsSet)
    {
        val[utility::conversions::to_string_t("id")] = ModelBase::toJson(m_Id);
    }
    if(m_EditableIsSet)
    {
        val[utility::conversions::to_string_t("editable")] = ModelBase::toJson(m_Editable);
    }
    if(m_NameIsSet)
    {
        val[utility::conversions::to_string_t("name")] = ModelBase::toJson(m_Name);
    }
    if(m_DescrIsSet)
    {
        val[utility::conversions::to_string_t("descr")] = ModelBase::toJson(m_Descr);
    }
    if(m_R_convectionIsSet)
    {
        val[utility::conversions::to_string_t("r_convection")] = ModelBase::toJson(m_R_convection);
    }
    if(m_C_convectionIsSet)
    {
        val[utility::conversions::to_string_t("c_convection")] = ModelBase::toJson(m_C_convection);
    }
    if(m_WidthIsSet)
    {
        val[utility::conversions::to_string_t("width")] = ModelBase::toJson(m_Width);
    }
    if(m_HeightIsSet)
    {
        val[utility::conversions::to_string_t("height")] = ModelBase::toJson(m_Height);
    }
    if(m_ThicknessIsSet)
    {
        val[utility::conversions::to_string_t("thickness")] = ModelBase::toJson(m_Thickness);
    }
    if(m_VersionIsSet)
    {
        val[utility::conversions::to_string_t("version")] = ModelBase::toJson(m_Version);
    }
    if(m_Current_versionIsSet)
    {
        val[utility::conversions::to_string_t("current_version")] = ModelBase::toJson(m_Current_version);
    }

    return val;
}

bool PCB::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t("id")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("id"));
        if(!fieldValue.is_null())
        {
            int32_t refVal_id;
            ok &= ModelBase::fromJson(fieldValue, refVal_id);
            setId(refVal_id);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("editable")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("editable"));
        if(!fieldValue.is_null())
        {
            bool refVal_editable;
            ok &= ModelBase::fromJson(fieldValue, refVal_editable);
            setEditable(refVal_editable);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("name")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("name"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_name;
            ok &= ModelBase::fromJson(fieldValue, refVal_name);
            setName(refVal_name);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("descr")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("descr"));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_descr;
            ok &= ModelBase::fromJson(fieldValue, refVal_descr);
            setDescr(refVal_descr);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("r_convection")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("r_convection"));
        if(!fieldValue.is_null())
        {
            double refVal_r_convection;
            ok &= ModelBase::fromJson(fieldValue, refVal_r_convection);
            setRConvection(refVal_r_convection);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("c_convection")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("c_convection"));
        if(!fieldValue.is_null())
        {
            double refVal_c_convection;
            ok &= ModelBase::fromJson(fieldValue, refVal_c_convection);
            setCConvection(refVal_c_convection);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("width")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("width"));
        if(!fieldValue.is_null())
        {
            double refVal_width;
            ok &= ModelBase::fromJson(fieldValue, refVal_width);
            setWidth(refVal_width);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("height")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("height"));
        if(!fieldValue.is_null())
        {
            double refVal_height;
            ok &= ModelBase::fromJson(fieldValue, refVal_height);
            setHeight(refVal_height);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("thickness")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("thickness"));
        if(!fieldValue.is_null())
        {
            double refVal_thickness;
            ok &= ModelBase::fromJson(fieldValue, refVal_thickness);
            setThickness(refVal_thickness);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("version")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("version"));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<PCBVersionSerialzer> refVal_version;
            ok &= ModelBase::fromJson(fieldValue, refVal_version);
            setVersion(refVal_version);
        }
    }
    if(val.has_field(utility::conversions::to_string_t("current_version")))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t("current_version"));
        if(!fieldValue.is_null())
        {
            int32_t refVal_current_version;
            ok &= ModelBase::fromJson(fieldValue, refVal_current_version);
            setCurrentVersion(refVal_current_version);
        }
    }
    return ok;
}

void PCB::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("id"), m_Id));
    }
    if(m_EditableIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("editable"), m_Editable));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("name"), m_Name));
    }
    if(m_DescrIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("descr"), m_Descr));
    }
    if(m_R_convectionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("r_convection"), m_R_convection));
    }
    if(m_C_convectionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("c_convection"), m_C_convection));
    }
    if(m_WidthIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("width"), m_Width));
    }
    if(m_HeightIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("height"), m_Height));
    }
    if(m_ThicknessIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("thickness"), m_Thickness));
    }
    if(m_VersionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("version"), m_Version));
    }
    if(m_Current_versionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t("current_version"), m_Current_version));
    }
}

bool PCB::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t("."))
    {
        namePrefix += utility::conversions::to_string_t(".");
    }

    if(multipart->hasContent(utility::conversions::to_string_t("id")))
    {
        int32_t refVal_id;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("id")), refVal_id );
        setId(refVal_id);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("editable")))
    {
        bool refVal_editable;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("editable")), refVal_editable );
        setEditable(refVal_editable);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("name")))
    {
        utility::string_t refVal_name;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("name")), refVal_name );
        setName(refVal_name);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("descr")))
    {
        utility::string_t refVal_descr;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("descr")), refVal_descr );
        setDescr(refVal_descr);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("r_convection")))
    {
        double refVal_r_convection;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("r_convection")), refVal_r_convection );
        setRConvection(refVal_r_convection);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("c_convection")))
    {
        double refVal_c_convection;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("c_convection")), refVal_c_convection );
        setCConvection(refVal_c_convection);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("width")))
    {
        double refVal_width;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("width")), refVal_width );
        setWidth(refVal_width);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("height")))
    {
        double refVal_height;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("height")), refVal_height );
        setHeight(refVal_height);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("thickness")))
    {
        double refVal_thickness;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("thickness")), refVal_thickness );
        setThickness(refVal_thickness);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("version")))
    {
        std::shared_ptr<PCBVersionSerialzer> refVal_version;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("version")), refVal_version );
        setVersion(refVal_version);
    }
    if(multipart->hasContent(utility::conversions::to_string_t("current_version")))
    {
        int32_t refVal_current_version;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t("current_version")), refVal_current_version );
        setCurrentVersion(refVal_current_version);
    }
    return ok;
}

int32_t PCB::getId() const
{
    return m_Id;
}

void PCB::setId(int32_t value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool PCB::idIsSet() const
{
    return m_IdIsSet;
}

void PCB::unsetId()
{
    m_IdIsSet = false;
}
bool PCB::isEditable() const
{
    return m_Editable;
}

void PCB::setEditable(bool value)
{
    m_Editable = value;
    m_EditableIsSet = true;
}

bool PCB::editableIsSet() const
{
    return m_EditableIsSet;
}

void PCB::unsetEditable()
{
    m_EditableIsSet = false;
}
utility::string_t PCB::getName() const
{
    return m_Name;
}

void PCB::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool PCB::nameIsSet() const
{
    return m_NameIsSet;
}

void PCB::unsetName()
{
    m_NameIsSet = false;
}
utility::string_t PCB::getDescr() const
{
    return m_Descr;
}

void PCB::setDescr(const utility::string_t& value)
{
    m_Descr = value;
    m_DescrIsSet = true;
}

bool PCB::descrIsSet() const
{
    return m_DescrIsSet;
}

void PCB::unsetDescr()
{
    m_DescrIsSet = false;
}
double PCB::getRConvection() const
{
    return m_R_convection;
}

void PCB::setRConvection(double value)
{
    m_R_convection = value;
    m_R_convectionIsSet = true;
}

bool PCB::rConvectionIsSet() const
{
    return m_R_convectionIsSet;
}

void PCB::unsetR_convection()
{
    m_R_convectionIsSet = false;
}
double PCB::getCConvection() const
{
    return m_C_convection;
}

void PCB::setCConvection(double value)
{
    m_C_convection = value;
    m_C_convectionIsSet = true;
}

bool PCB::cConvectionIsSet() const
{
    return m_C_convectionIsSet;
}

void PCB::unsetC_convection()
{
    m_C_convectionIsSet = false;
}
double PCB::getWidth() const
{
    return m_Width;
}

void PCB::setWidth(double value)
{
    m_Width = value;
    m_WidthIsSet = true;
}

bool PCB::widthIsSet() const
{
    return m_WidthIsSet;
}

void PCB::unsetWidth()
{
    m_WidthIsSet = false;
}
double PCB::getHeight() const
{
    return m_Height;
}

void PCB::setHeight(double value)
{
    m_Height = value;
    m_HeightIsSet = true;
}

bool PCB::heightIsSet() const
{
    return m_HeightIsSet;
}

void PCB::unsetHeight()
{
    m_HeightIsSet = false;
}
double PCB::getThickness() const
{
    return m_Thickness;
}

void PCB::setThickness(double value)
{
    m_Thickness = value;
    m_ThicknessIsSet = true;
}

bool PCB::thicknessIsSet() const
{
    return m_ThicknessIsSet;
}

void PCB::unsetThickness()
{
    m_ThicknessIsSet = false;
}
std::shared_ptr<PCBVersionSerialzer> PCB::getVersion() const
{
    return m_Version;
}

void PCB::setVersion(const std::shared_ptr<PCBVersionSerialzer>& value)
{
    m_Version = value;
    m_VersionIsSet = true;
}

bool PCB::versionIsSet() const
{
    return m_VersionIsSet;
}

void PCB::unsetVersion()
{
    m_VersionIsSet = false;
}
int32_t PCB::getCurrentVersion() const
{
    return m_Current_version;
}

void PCB::setCurrentVersion(int32_t value)
{
    m_Current_version = value;
    m_Current_versionIsSet = true;
}

bool PCB::currentVersionIsSet() const
{
    return m_Current_versionIsSet;
}

void PCB::unsetCurrent_version()
{
    m_Current_versionIsSet = false;
}
}
}


