/**
 * PowerMeter API
 * API
 *
 * The version of the OpenAPI document: 2021.4.1
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * PCB.h
 *
 * 
 */

#ifndef POWERMETER_MODEL_PCB_H_
#define POWERMETER_MODEL_PCB_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "PCBVersionSerialzer.h"

namespace powermeter {
namespace model {


/// <summary>
/// 
/// </summary>
class  PCB
    : public ModelBase
{
public:
    PCB();
    virtual ~PCB();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// PCB members

    /// <summary>
    /// 
    /// </summary>
    int32_t getId() const;
    bool idIsSet() const;
    void unsetId();

    void setId(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    bool isEditable() const;
    bool editableIsSet() const;
    void unsetEditable();

    void setEditable(bool value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();

    void setName(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getDescr() const;
    bool descrIsSet() const;
    void unsetDescr();

    void setDescr(const utility::string_t& value);

    /// <summary>
    /// 
    /// </summary>
    double getRConvection() const;
    bool rConvectionIsSet() const;
    void unsetR_convection();

    void setRConvection(double value);

    /// <summary>
    /// 
    /// </summary>
    double getCConvection() const;
    bool cConvectionIsSet() const;
    void unsetC_convection();

    void setCConvection(double value);

    /// <summary>
    /// 
    /// </summary>
    double getWidth() const;
    bool widthIsSet() const;
    void unsetWidth();

    void setWidth(double value);

    /// <summary>
    /// 
    /// </summary>
    double getHeight() const;
    bool heightIsSet() const;
    void unsetHeight();

    void setHeight(double value);

    /// <summary>
    /// 
    /// </summary>
    double getThickness() const;
    bool thicknessIsSet() const;
    void unsetThickness();

    void setThickness(double value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<PCBVersionSerialzer> getVersion() const;
    bool versionIsSet() const;
    void unsetVersion();

    void setVersion(const std::shared_ptr<PCBVersionSerialzer>& value);

    /// <summary>
    /// 
    /// </summary>
    int32_t getCurrentVersion() const;
    bool currentVersionIsSet() const;
    void unsetCurrent_version();

    void setCurrentVersion(int32_t value);


protected:
    int32_t m_Id;
    bool m_IdIsSet;
    bool m_Editable;
    bool m_EditableIsSet;
    utility::string_t m_Name;
    bool m_NameIsSet;
    utility::string_t m_Descr;
    bool m_DescrIsSet;
    double m_R_convection;
    bool m_R_convectionIsSet;
    double m_C_convection;
    bool m_C_convectionIsSet;
    double m_Width;
    bool m_WidthIsSet;
    double m_Height;
    bool m_HeightIsSet;
    double m_Thickness;
    bool m_ThicknessIsSet;
    std::shared_ptr<PCBVersionSerialzer> m_Version;
    bool m_VersionIsSet;
    int32_t m_Current_version;
    bool m_Current_versionIsSet;
};


}
}

#endif /* POWERMETER_MODEL_PCB_H_ */
