# coding: utf-8

"""
    PowerMeter API

    API  # noqa: E501

    The version of the OpenAPI document: 2021.4.1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import powermeter_api
from powermeter_api.api.design_api import DesignApi  # noqa: E501
from powermeter_api.rest import ApiException


class TestDesignApi(unittest.TestCase):
    """DesignApi unit test stubs"""

    def setUp(self):
        self.api = powermeter_api.api.design_api.DesignApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_design_hierarchy_delete_all(self):
        """Test case for api_design_hierarchy_delete_all

        """
        pass

    def test_api_design_instance_delete_all(self):
        """Test case for api_design_instance_delete_all

        """
        pass

    def test_api_design_mode_delete_all(self):
        """Test case for api_design_mode_delete_all

        """
        pass

    def test_api_design_parameter_delete_all(self):
        """Test case for api_design_parameter_delete_all

        """
        pass

    def test_api_design_supply_delete_all(self):
        """Test case for api_design_supply_delete_all

        """
        pass

    def test_design_commit_create(self):
        """Test case for design_commit_create

        """
        pass

    def test_design_computepower_create(self):
        """Test case for design_computepower_create

        """
        pass

    def test_design_computepowerarc_create(self):
        """Test case for design_computepowerarc_create

        """
        pass

    def test_design_contribpower_compute1_list(self):
        """Test case for design_contribpower_compute1_list

        """
        pass

    def test_design_contribpower_compute_list(self):
        """Test case for design_contribpower_compute_list

        """
        pass

    def test_design_contribpower_create(self):
        """Test case for design_contribpower_create

        """
        pass

    def test_design_contribpower_delete(self):
        """Test case for design_contribpower_delete

        """
        pass

    def test_design_contribpower_list(self):
        """Test case for design_contribpower_list

        """
        pass

    def test_design_contribpower_read(self):
        """Test case for design_contribpower_read

        """
        pass

    def test_design_contribpower_update(self):
        """Test case for design_contribpower_update

        """
        pass

    def test_design_dashboard_access_create(self):
        """Test case for design_dashboard_access_create

        """
        pass

    def test_design_dashboard_clone_create(self):
        """Test case for design_dashboard_clone_create

        """
        pass

    def test_design_dashboard_column_create(self):
        """Test case for design_dashboard_column_create

        """
        pass

    def test_design_dashboard_column_delete(self):
        """Test case for design_dashboard_column_delete

        """
        pass

    def test_design_dashboard_column_list(self):
        """Test case for design_dashboard_column_list

        """
        pass

    def test_design_dashboard_column_read(self):
        """Test case for design_dashboard_column_read

        """
        pass

    def test_design_dashboard_column_update(self):
        """Test case for design_dashboard_column_update

        """
        pass

    def test_design_dashboard_create(self):
        """Test case for design_dashboard_create

        """
        pass

    def test_design_dashboard_data_list(self):
        """Test case for design_dashboard_data_list

        """
        pass

    def test_design_dashboard_delete(self):
        """Test case for design_dashboard_delete

        """
        pass

    def test_design_dashboard_list(self):
        """Test case for design_dashboard_list

        """
        pass

    def test_design_dashboard_read(self):
        """Test case for design_dashboard_read

        """
        pass

    def test_design_dashboard_row_create(self):
        """Test case for design_dashboard_row_create

        """
        pass

    def test_design_dashboard_row_delete(self):
        """Test case for design_dashboard_row_delete

        """
        pass

    def test_design_dashboard_row_list(self):
        """Test case for design_dashboard_row_list

        """
        pass

    def test_design_dashboard_row_read(self):
        """Test case for design_dashboard_row_read

        """
        pass

    def test_design_dashboard_row_update(self):
        """Test case for design_dashboard_row_update

        """
        pass

    def test_design_dashboard_update(self):
        """Test case for design_dashboard_update

        """
        pass

    def test_design_dashboard_update_list(self):
        """Test case for design_dashboard_update_list

        """
        pass

    def test_design_data_create(self):
        """Test case for design_data_create

        """
        pass

    def test_design_data_delete(self):
        """Test case for design_data_delete

        """
        pass

    def test_design_data_list(self):
        """Test case for design_data_list

        """
        pass

    def test_design_data_read(self):
        """Test case for design_data_read

        """
        pass

    def test_design_data_update(self):
        """Test case for design_data_update

        """
        pass

    def test_design_energy_create(self):
        """Test case for design_energy_create

        """
        pass

    def test_design_energy_list(self):
        """Test case for design_energy_list

        """
        pass

    def test_design_ff_create(self):
        """Test case for design_ff_create

        """
        pass

    def test_design_ff_delete(self):
        """Test case for design_ff_delete

        """
        pass

    def test_design_ff_list(self):
        """Test case for design_ff_list

        """
        pass

    def test_design_ff_read(self):
        """Test case for design_ff_read

        """
        pass

    def test_design_ff_update(self):
        """Test case for design_ff_update

        """
        pass

    def test_design_hierarchy_group_create(self):
        """Test case for design_hierarchy_group_create

        """
        pass

    def test_design_hierarchy_group_delete(self):
        """Test case for design_hierarchy_group_delete

        """
        pass

    def test_design_hierarchy_group_update(self):
        """Test case for design_hierarchy_group_update

        """
        pass

    def test_design_hierarchy_list(self):
        """Test case for design_hierarchy_list

        """
        pass

    def test_design_hierarchy_update(self):
        """Test case for design_hierarchy_update

        """
        pass

    def test_design_instance_bulk_create(self):
        """Test case for design_instance_bulk_create

        """
        pass

    def test_design_instance_clone(self):
        """Test case for design_instance_clone

        """
        pass

    def test_design_instance_create(self):
        """Test case for design_instance_create

        """
        pass

    def test_design_instance_delete(self):
        """Test case for design_instance_delete

        """
        pass

    def test_design_instance_list(self):
        """Test case for design_instance_list

        """
        pass

    def test_design_instance_read(self):
        """Test case for design_instance_read

        """
        pass

    def test_design_instance_supply_create(self):
        """Test case for design_instance_supply_create

        """
        pass

    def test_design_instance_supply_list(self):
        """Test case for design_instance_supply_list

        """
        pass

    def test_design_instance_supply_read(self):
        """Test case for design_instance_supply_read

        """
        pass

    def test_design_instance_supply_update(self):
        """Test case for design_instance_supply_update

        """
        pass

    def test_design_instance_update(self):
        """Test case for design_instance_update

        """
        pass

    def test_design_instance_updatemaster_create(self):
        """Test case for design_instance_updatemaster_create

        """
        pass

    def test_design_instantiable_list(self):
        """Test case for design_instantiable_list

        """
        pass

    def test_design_latch_create(self):
        """Test case for design_latch_create

        """
        pass

    def test_design_latch_delete(self):
        """Test case for design_latch_delete

        """
        pass

    def test_design_latch_list(self):
        """Test case for design_latch_list

        """
        pass

    def test_design_latch_read(self):
        """Test case for design_latch_read

        """
        pass

    def test_design_latch_update(self):
        """Test case for design_latch_update

        """
        pass

    def test_design_leakagepower_create(self):
        """Test case for design_leakagepower_create

        """
        pass

    def test_design_leakagepower_delete(self):
        """Test case for design_leakagepower_delete

        """
        pass

    def test_design_leakagepower_list(self):
        """Test case for design_leakagepower_list

        """
        pass

    def test_design_leakagepower_read(self):
        """Test case for design_leakagepower_read

        """
        pass

    def test_design_leakagepower_update(self):
        """Test case for design_leakagepower_update

        """
        pass

    def test_design_mode_clone(self):
        """Test case for design_mode_clone

        """
        pass

    def test_design_mode_create(self):
        """Test case for design_mode_create

        """
        pass

    def test_design_mode_delete(self):
        """Test case for design_mode_delete

        """
        pass

    def test_design_mode_list(self):
        """Test case for design_mode_list

        """
        pass

    def test_design_mode_power_list(self):
        """Test case for design_mode_power_list

        """
        pass

    def test_design_mode_powerdistribution_list(self):
        """Test case for design_mode_powerdistribution_list

        """
        pass

    def test_design_mode_read(self):
        """Test case for design_mode_read

        """
        pass

    def test_design_mode_supply_computepower_create(self):
        """Test case for design_mode_supply_computepower_create

        """
        pass

    def test_design_mode_supply_computepowertable_create(self):
        """Test case for design_mode_supply_computepowertable_create

        """
        pass

    def test_design_mode_supplystate_list(self):
        """Test case for design_mode_supplystate_list

        """
        pass

    def test_design_mode_supplystate_update(self):
        """Test case for design_mode_supplystate_update

        """
        pass

    def test_design_mode_update(self):
        """Test case for design_mode_update

        """
        pass

    def test_design_parameter_clone(self):
        """Test case for design_parameter_clone

        """
        pass

    def test_design_parameter_create(self):
        """Test case for design_parameter_create

        """
        pass

    def test_design_parameter_delete(self):
        """Test case for design_parameter_delete

        """
        pass

    def test_design_parameter_list(self):
        """Test case for design_parameter_list

        """
        pass

    def test_design_parameter_read(self):
        """Test case for design_parameter_read

        """
        pass

    def test_design_parameter_update(self):
        """Test case for design_parameter_update

        """
        pass

    def test_design_permissions_list(self):
        """Test case for design_permissions_list

        """
        pass

    def test_design_permissions_update(self):
        """Test case for design_permissions_update

        """
        pass

    def test_design_pin_caps_create(self):
        """Test case for design_pin_caps_create

        """
        pass

    def test_design_pin_caps_delete(self):
        """Test case for design_pin_caps_delete

        """
        pass

    def test_design_pin_caps_list(self):
        """Test case for design_pin_caps_list

        """
        pass

    def test_design_pin_caps_read(self):
        """Test case for design_pin_caps_read

        """
        pass

    def test_design_pin_caps_update(self):
        """Test case for design_pin_caps_update

        """
        pass

    def test_design_pin_create(self):
        """Test case for design_pin_create

        """
        pass

    def test_design_pin_delete(self):
        """Test case for design_pin_delete

        """
        pass

    def test_design_pin_energy_create(self):
        """Test case for design_pin_energy_create

        """
        pass

    def test_design_pin_energy_delete(self):
        """Test case for design_pin_energy_delete

        """
        pass

    def test_design_pin_energy_list(self):
        """Test case for design_pin_energy_list

        """
        pass

    def test_design_pin_energy_read(self):
        """Test case for design_pin_energy_read

        """
        pass

    def test_design_pin_energy_update(self):
        """Test case for design_pin_energy_update

        """
        pass

    def test_design_pin_list(self):
        """Test case for design_pin_list

        """
        pass

    def test_design_pin_read(self):
        """Test case for design_pin_read

        """
        pass

    def test_design_pin_update(self):
        """Test case for design_pin_update

        """
        pass

    def test_design_power_create(self):
        """Test case for design_power_create

        """
        pass

    def test_design_power_delete(self):
        """Test case for design_power_delete

        """
        pass

    def test_design_power_list(self):
        """Test case for design_power_list

        """
        pass

    def test_design_power_read(self):
        """Test case for design_power_read

        """
        pass

    def test_design_power_update(self):
        """Test case for design_power_update

        """
        pass

    def test_design_read(self):
        """Test case for design_read

        """
        pass

    def test_design_restore_create(self):
        """Test case for design_restore_create

        """
        pass

    def test_design_scenario_clone(self):
        """Test case for design_scenario_clone

        """
        pass

    def test_design_scenario_create(self):
        """Test case for design_scenario_create

        """
        pass

    def test_design_scenario_delete(self):
        """Test case for design_scenario_delete

        """
        pass

    def test_design_scenario_list(self):
        """Test case for design_scenario_list

        """
        pass

    def test_design_scenario_mode_config_delete(self):
        """Test case for design_scenario_mode_config_delete

        """
        pass

    def test_design_scenario_mode_config_read(self):
        """Test case for design_scenario_mode_config_read

        """
        pass

    def test_design_scenario_mode_config_update(self):
        """Test case for design_scenario_mode_config_update

        """
        pass

    def test_design_scenario_mode_create(self):
        """Test case for design_scenario_mode_create

        """
        pass

    def test_design_scenario_mode_read(self):
        """Test case for design_scenario_mode_read

        """
        pass

    def test_design_scenario_param_config_delete(self):
        """Test case for design_scenario_param_config_delete

        """
        pass

    def test_design_scenario_param_config_read(self):
        """Test case for design_scenario_param_config_read

        """
        pass

    def test_design_scenario_param_config_update(self):
        """Test case for design_scenario_param_config_update

        """
        pass

    def test_design_scenario_param_create(self):
        """Test case for design_scenario_param_create

        """
        pass

    def test_design_scenario_param_read(self):
        """Test case for design_scenario_param_read

        """
        pass

    def test_design_scenario_power_list(self):
        """Test case for design_scenario_power_list

        """
        pass

    def test_design_scenario_powerdistribution_list(self):
        """Test case for design_scenario_powerdistribution_list

        """
        pass

    def test_design_scenario_read(self):
        """Test case for design_scenario_read

        """
        pass

    def test_design_scenario_supply_config_delete(self):
        """Test case for design_scenario_supply_config_delete

        """
        pass

    def test_design_scenario_supply_config_read(self):
        """Test case for design_scenario_supply_config_read

        """
        pass

    def test_design_scenario_supply_config_update(self):
        """Test case for design_scenario_supply_config_update

        """
        pass

    def test_design_scenario_supply_create(self):
        """Test case for design_scenario_supply_create

        """
        pass

    def test_design_scenario_supply_read(self):
        """Test case for design_scenario_supply_read

        """
        pass

    def test_design_scenario_trend_list(self):
        """Test case for design_scenario_trend_list

        """
        pass

    def test_design_scenario_update(self):
        """Test case for design_scenario_update

        """
        pass

    def test_design_scenario_update_list(self):
        """Test case for design_scenario_update_list

        """
        pass

    def test_design_sensor_clone(self):
        """Test case for design_sensor_clone

        """
        pass

    def test_design_sensor_create(self):
        """Test case for design_sensor_create

        """
        pass

    def test_design_sensor_delete(self):
        """Test case for design_sensor_delete

        """
        pass

    def test_design_sensor_list(self):
        """Test case for design_sensor_list

        """
        pass

    def test_design_sensor_read(self):
        """Test case for design_sensor_read

        """
        pass

    def test_design_sensor_update(self):
        """Test case for design_sensor_update

        """
        pass

    def test_design_statetable_create(self):
        """Test case for design_statetable_create

        """
        pass

    def test_design_statetable_delete(self):
        """Test case for design_statetable_delete

        """
        pass

    def test_design_statetable_list(self):
        """Test case for design_statetable_list

        """
        pass

    def test_design_statetable_read(self):
        """Test case for design_statetable_read

        """
        pass

    def test_design_statetable_update(self):
        """Test case for design_statetable_update

        """
        pass

    def test_design_supply_clone(self):
        """Test case for design_supply_clone

        """
        pass

    def test_design_supply_create(self):
        """Test case for design_supply_create

        """
        pass

    def test_design_supply_delete(self):
        """Test case for design_supply_delete

        """
        pass

    def test_design_supply_list(self):
        """Test case for design_supply_list

        """
        pass

    def test_design_supply_modestate_list(self):
        """Test case for design_supply_modestate_list

        """
        pass

    def test_design_supply_modestate_update(self):
        """Test case for design_supply_modestate_update

        """
        pass

    def test_design_supply_read(self):
        """Test case for design_supply_read

        """
        pass

    def test_design_supply_update(self):
        """Test case for design_supply_update

        """
        pass

    def test_design_supplymodestate_list(self):
        """Test case for design_supplymodestate_list

        """
        pass

    def test_design_supplymodestate_update(self):
        """Test case for design_supplymodestate_update

        """
        pass

    def test_design_trend_create(self):
        """Test case for design_trend_create

        """
        pass

    def test_design_trend_delete(self):
        """Test case for design_trend_delete

        """
        pass

    def test_design_trend_list(self):
        """Test case for design_trend_list

        """
        pass

    def test_design_trend_read(self):
        """Test case for design_trend_read

        """
        pass

    def test_design_trend_update(self):
        """Test case for design_trend_update

        """
        pass

    def test_design_update(self):
        """Test case for design_update

        """
        pass

    def test_design_update_list(self):
        """Test case for design_update_list

        """
        pass

    def test_design_verilog_instances_list(self):
        """Test case for design_verilog_instances_list

        """
        pass

    def test_design_verilog_list(self):
        """Test case for design_verilog_list

        """
        pass

    def test_design_verilog_module_state_list(self):
        """Test case for design_verilog_module_state_list

        """
        pass

    def test_design_verilog_modules_list(self):
        """Test case for design_verilog_modules_list

        """
        pass

    def test_design_verilog_wire_state_list(self):
        """Test case for design_verilog_wire_state_list

        """
        pass

    def test_design_verilog_wires_list(self):
        """Test case for design_verilog_wires_list

        """
        pass

    def test_design_version_list(self):
        """Test case for design_version_list

        """
        pass

    def test_design_version_read(self):
        """Test case for design_version_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
