/**
 * PowerMeter API
 * API
 *
 * The version of the OpenAPI document: 2021.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PowermeterApi);
  }
}(this, function(expect, PowermeterApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PowermeterApi.ContribPower();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ContribPower', function() {
    it('should create an instance of ContribPower', function() {
      // uncomment below and update the code to test ContribPower
      //var instane = new PowermeterApi.ContribPower();
      //expect(instance).to.be.a(PowermeterApi.ContribPower);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new PowermeterApi.ContribPower();
      //expect(instance).to.be();
    });

    it('should have the property when (base name: "when")', function() {
      // uncomment below and update the code to test the property when
      //var instane = new PowermeterApi.ContribPower();
      //expect(instance).to.be();
    });

    it('should have the property contributors (base name: "contributors")', function() {
      // uncomment below and update the code to test the property contributors
      //var instane = new PowermeterApi.ContribPower();
      //expect(instance).to.be();
    });

    it('should have the property modes (base name: "modes")', function() {
      // uncomment below and update the code to test the property modes
      //var instane = new PowermeterApi.ContribPower();
      //expect(instance).to.be();
    });

  });

}));
