/**
 * PowerMeter API
 * API
 *
 * The version of the OpenAPI document: 2021.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PowermeterApi);
  }
}(this, function(expect, PowermeterApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new PowermeterApi.DesignAccess();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DesignAccess', function() {
    it('should create an instance of DesignAccess', function() {
      // uncomment below and update the code to test DesignAccess
      //var instane = new PowermeterApi.DesignAccess();
      //expect(instance).to.be.a(PowermeterApi.DesignAccess);
    });

    it('should have the property master (base name: "master")', function() {
      // uncomment below and update the code to test the property master
      //var instane = new PowermeterApi.DesignAccess();
      //expect(instance).to.be();
    });

    it('should have the property masterName (base name: "master_name")', function() {
      // uncomment below and update the code to test the property masterName
      //var instane = new PowermeterApi.DesignAccess();
      //expect(instance).to.be();
    });

    it('should have the property project (base name: "project")', function() {
      // uncomment below and update the code to test the property project
      //var instane = new PowermeterApi.DesignAccess();
      //expect(instance).to.be();
    });

    it('should have the property projectName (base name: "project_name")', function() {
      // uncomment below and update the code to test the property projectName
      //var instane = new PowermeterApi.DesignAccess();
      //expect(instance).to.be();
    });

    it('should have the property timestamp (base name: "timestamp")', function() {
      // uncomment below and update the code to test the property timestamp
      //var instane = new PowermeterApi.DesignAccess();
      //expect(instance).to.be();
    });

  });

}));
