/**
 * PowerMeter API
 * API
 *
 * The version of the OpenAPI document: 2021.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DashboardRow model module.
 * @module model/DashboardRow
 * @version 2021.4.1
 */
class DashboardRow {
    /**
     * Constructs a new <code>DashboardRow</code>.
     * @alias module:model/DashboardRow
     * @param title {String} 
     * @param order {Number} 
     * @param field {String} 
     */
    constructor(title, order, field) { 
        
        DashboardRow.initialize(this, title, order, field);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title, order, field) { 
        obj['title'] = title;
        obj['order'] = order;
        obj['field'] = field;
    }

    /**
     * Constructs a <code>DashboardRow</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DashboardRow} obj Optional instance to populate.
     * @return {module:model/DashboardRow} The populated <code>DashboardRow</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DashboardRow();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('order')) {
                obj['order'] = ApiClient.convertToType(data['order'], 'Number');
            }
            if (data.hasOwnProperty('field')) {
                obj['field'] = ApiClient.convertToType(data['field'], 'String');
            }
            if (data.hasOwnProperty('format')) {
                obj['format'] = ApiClient.convertToType(data['format'], 'String');
            }
            if (data.hasOwnProperty('units')) {
                obj['units'] = ApiClient.convertToType(data['units'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
DashboardRow.prototype['id'] = undefined;

/**
 * @member {String} title
 */
DashboardRow.prototype['title'] = undefined;

/**
 * @member {Number} order
 */
DashboardRow.prototype['order'] = undefined;

/**
 * @member {String} field
 */
DashboardRow.prototype['field'] = undefined;

/**
 * @member {String} format
 */
DashboardRow.prototype['format'] = undefined;

/**
 * @member {String} units
 */
DashboardRow.prototype['units'] = undefined;






export default DashboardRow;

