/**
 * PowerMeter API
 * API
 *
 * The version of the OpenAPI document: 2021.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DesignScenario model module.
 * @module model/DesignScenario
 * @version 2021.4.1
 */
class DesignScenario {
    /**
     * Constructs a new <code>DesignScenario</code>.
     * @alias module:model/DesignScenario
     * @param descr {String} 
     * @param temperature {Number} 
     */
    constructor(descr, temperature) { 
        
        DesignScenario.initialize(this, descr, temperature);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, descr, temperature) { 
        obj['descr'] = descr;
        obj['temperature'] = temperature;
    }

    /**
     * Constructs a <code>DesignScenario</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DesignScenario} obj Optional instance to populate.
     * @return {module:model/DesignScenario} The populated <code>DesignScenario</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DesignScenario();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('descr')) {
                obj['descr'] = ApiClient.convertToType(data['descr'], 'String');
            }
            if (data.hasOwnProperty('temperature')) {
                obj['temperature'] = ApiClient.convertToType(data['temperature'], 'Number');
            }
            if (data.hasOwnProperty('process')) {
                obj['process'] = ApiClient.convertToType(data['process'], 'Number');
            }
            if (data.hasOwnProperty('rc')) {
                obj['rc'] = ApiClient.convertToType(data['rc'], 'Number');
            }
            if (data.hasOwnProperty('endtime')) {
                obj['endtime'] = ApiClient.convertToType(data['endtime'], 'Number');
            }
            if (data.hasOwnProperty('average_power')) {
                obj['average_power'] = ApiClient.convertToType(data['average_power'], 'Number');
            }
            if (data.hasOwnProperty('total_energy')) {
                obj['total_energy'] = ApiClient.convertToType(data['total_energy'], 'Number');
            }
            if (data.hasOwnProperty('confidence')) {
                obj['confidence'] = ApiClient.convertToType(data['confidence'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
DesignScenario.prototype['id'] = undefined;

/**
 * @member {String} descr
 */
DesignScenario.prototype['descr'] = undefined;

/**
 * @member {Number} temperature
 */
DesignScenario.prototype['temperature'] = undefined;

/**
 * @member {Number} process
 */
DesignScenario.prototype['process'] = undefined;

/**
 * @member {Number} rc
 */
DesignScenario.prototype['rc'] = undefined;

/**
 * @member {Number} endtime
 */
DesignScenario.prototype['endtime'] = undefined;

/**
 * @member {Number} average_power
 */
DesignScenario.prototype['average_power'] = undefined;

/**
 * @member {Number} total_energy
 */
DesignScenario.prototype['total_energy'] = undefined;

/**
 * @member {Number} confidence
 */
DesignScenario.prototype['confidence'] = undefined;






export default DesignScenario;

