/**
 * PowerMeter API
 * API
 *
 * The version of the OpenAPI document: 2021.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HeatsinkVersion from './HeatsinkVersion';

/**
 * The Heatsink model module.
 * @module model/Heatsink
 * @version 2021.4.1
 */
class Heatsink {
    /**
     * Constructs a new <code>Heatsink</code>.
     * @alias module:model/Heatsink
     */
    constructor() { 
        
        Heatsink.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Heatsink</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Heatsink} obj Optional instance to populate.
     * @return {module:model/Heatsink} The populated <code>Heatsink</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Heatsink();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('descr')) {
                obj['descr'] = ApiClient.convertToType(data['descr'], 'String');
            }
            if (data.hasOwnProperty('editable')) {
                obj['editable'] = ApiClient.convertToType(data['editable'], 'Boolean');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = HeatsinkVersion.constructFromObject(data['version']);
            }
            if (data.hasOwnProperty('current_version')) {
                obj['current_version'] = ApiClient.convertToType(data['current_version'], 'String');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'Number');
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], 'Number');
            }
            if (data.hasOwnProperty('thickness')) {
                obj['thickness'] = ApiClient.convertToType(data['thickness'], 'Number');
            }
            if (data.hasOwnProperty('r_convec')) {
                obj['r_convec'] = ApiClient.convertToType(data['r_convec'], 'Number');
            }
            if (data.hasOwnProperty('c_convec')) {
                obj['c_convec'] = ApiClient.convertToType(data['c_convec'], 'Number');
            }
            if (data.hasOwnProperty('conductivity')) {
                obj['conductivity'] = ApiClient.convertToType(data['conductivity'], 'Number');
            }
            if (data.hasOwnProperty('heatcapacity')) {
                obj['heatcapacity'] = ApiClient.convertToType(data['heatcapacity'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Heatsink.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Heatsink.prototype['name'] = undefined;

/**
 * @member {String} descr
 */
Heatsink.prototype['descr'] = undefined;

/**
 * @member {Boolean} editable
 */
Heatsink.prototype['editable'] = undefined;

/**
 * @member {module:model/HeatsinkVersion} version
 */
Heatsink.prototype['version'] = undefined;

/**
 * @member {String} current_version
 */
Heatsink.prototype['current_version'] = undefined;

/**
 * @member {Number} width
 */
Heatsink.prototype['width'] = undefined;

/**
 * @member {Number} height
 */
Heatsink.prototype['height'] = undefined;

/**
 * @member {Number} thickness
 */
Heatsink.prototype['thickness'] = undefined;

/**
 * @member {Number} r_convec
 */
Heatsink.prototype['r_convec'] = undefined;

/**
 * @member {Number} c_convec
 */
Heatsink.prototype['c_convec'] = undefined;

/**
 * @member {Number} conductivity
 */
Heatsink.prototype['conductivity'] = undefined;

/**
 * @member {Number} heatcapacity
 */
Heatsink.prototype['heatcapacity'] = undefined;






export default Heatsink;

