/**
 * PowerMeter API
 * API
 *
 * The version of the OpenAPI document: 2021.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RCCorner model module.
 * @module model/RCCorner
 * @version 2021.4.1
 */
class RCCorner {
    /**
     * Constructs a new <code>RCCorner</code>.
     * @alias module:model/RCCorner
     * @param name {String} 
     * @param type {Number} 
     */
    constructor(name, type) { 
        
        RCCorner.initialize(this, name, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, type) { 
        obj['name'] = name;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>RCCorner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RCCorner} obj Optional instance to populate.
     * @return {module:model/RCCorner} The populated <code>RCCorner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RCCorner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
RCCorner.prototype['id'] = undefined;

/**
 * @member {String} name
 */
RCCorner.prototype['name'] = undefined;

/**
 * @member {Number} type
 */
RCCorner.prototype['type'] = undefined;






export default RCCorner;

