/**
 * PowerMeter API
 * API
 *
 * The version of the OpenAPI document: 2021.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SimScope model module.
 * @module model/SimScope
 * @version 2021.4.1
 */
class SimScope {
    /**
     * Constructs a new <code>SimScope</code>.
     * @alias module:model/SimScope
     * @param name {String} 
     * @param type {String} 
     */
    constructor(name, type) { 
        
        SimScope.initialize(this, name, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, type) { 
        obj['name'] = name;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>SimScope</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SimScope} obj Optional instance to populate.
     * @return {module:model/SimScope} The populated <code>SimScope</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SimScope();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('scope')) {
                obj['scope'] = ApiClient.convertToType(data['scope'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
SimScope.prototype['id'] = undefined;

/**
 * @member {Number} scope
 */
SimScope.prototype['scope'] = undefined;

/**
 * @member {String} name
 */
SimScope.prototype['name'] = undefined;

/**
 * @member {String} type
 */
SimScope.prototype['type'] = undefined;






export default SimScope;

