/**
 * PowerMeter API
 * API
 *
 * The version of the OpenAPI document: 2021.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SwaggerContribDevices model module.
 * @module model/SwaggerContribDevices
 * @version 2021.4.1
 */
class SwaggerContribDevices {
    /**
     * Constructs a new <code>SwaggerContribDevices</code>.
     * @alias module:model/SwaggerContribDevices
     * @param name {String} 
     * @param length {Number} 
     * @param count {Number} 
     */
    constructor(name, length, count) { 
        
        SwaggerContribDevices.initialize(this, name, length, count);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, length, count) { 
        obj['name'] = name;
        obj['length'] = length;
        obj['count'] = count;
    }

    /**
     * Constructs a <code>SwaggerContribDevices</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SwaggerContribDevices} obj Optional instance to populate.
     * @return {module:model/SwaggerContribDevices} The populated <code>SwaggerContribDevices</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SwaggerContribDevices();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('length')) {
                obj['length'] = ApiClient.convertToType(data['length'], 'Number');
            }
            if (data.hasOwnProperty('width')) {
                obj['width'] = ApiClient.convertToType(data['width'], 'Number');
            }
            if (data.hasOwnProperty('nfin')) {
                obj['nfin'] = ApiClient.convertToType(data['nfin'], 'Number');
            }
            if (data.hasOwnProperty('count')) {
                obj['count'] = ApiClient.convertToType(data['count'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} name
 */
SwaggerContribDevices.prototype['name'] = undefined;

/**
 * @member {Number} length
 */
SwaggerContribDevices.prototype['length'] = undefined;

/**
 * @member {Number} width
 */
SwaggerContribDevices.prototype['width'] = undefined;

/**
 * @member {Number} nfin
 */
SwaggerContribDevices.prototype['nfin'] = undefined;

/**
 * @member {Number} count
 */
SwaggerContribDevices.prototype['count'] = undefined;






export default SwaggerContribDevices;

