/**
 * PowerMeter API
 * API
 *
 * The version of the OpenAPI document: 2021.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WLMVersion model module.
 * @module model/WLMVersion
 * @version 2021.4.1
 */
class WLMVersion {
    /**
     * Constructs a new <code>WLMVersion</code>.
     * @alias module:model/WLMVersion
     * @param descr {String} 
     */
    constructor(descr) { 
        
        WLMVersion.initialize(this, descr);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, descr) { 
        obj['descr'] = descr;
    }

    /**
     * Constructs a <code>WLMVersion</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WLMVersion} obj Optional instance to populate.
     * @return {module:model/WLMVersion} The populated <code>WLMVersion</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WLMVersion();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('descr')) {
                obj['descr'] = ApiClient.convertToType(data['descr'], 'String');
            }
            if (data.hasOwnProperty('wlm')) {
                obj['wlm'] = ApiClient.convertToType(data['wlm'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
WLMVersion.prototype['id'] = undefined;

/**
 * @member {Date} timestamp
 */
WLMVersion.prototype['timestamp'] = undefined;

/**
 * @member {Number} version
 */
WLMVersion.prototype['version'] = undefined;

/**
 * @member {String} descr
 */
WLMVersion.prototype['descr'] = undefined;

/**
 * @member {Number} wlm
 */
WLMVersion.prototype['wlm'] = undefined;






export default WLMVersion;

