# coding: utf-8

"""
    PowerMeter API

    API  # noqa: E501

    The version of the OpenAPI document: 2021.4.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from powermeter_api.configuration import Configuration


class ContribPower(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'when': 'str',
        'contributors': 'list[ContribPowerDevice]',
        'modes': 'list[int]'
    }

    attribute_map = {
        'id': 'id',
        'when': 'when',
        'contributors': 'contributors',
        'modes': 'modes'
    }

    def __init__(self, id=None, when=None, contributors=None, modes=None, local_vars_configuration=None):  # noqa: E501
        """ContribPower - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._when = None
        self._contributors = None
        self._modes = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.when = when
        self.contributors = contributors
        if modes is not None:
            self.modes = modes

    @property
    def id(self):
        """Gets the id of this ContribPower.  # noqa: E501


        :return: The id of this ContribPower.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ContribPower.


        :param id: The id of this ContribPower.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def when(self):
        """Gets the when of this ContribPower.  # noqa: E501


        :return: The when of this ContribPower.  # noqa: E501
        :rtype: str
        """
        return self._when

    @when.setter
    def when(self, when):
        """Sets the when of this ContribPower.


        :param when: The when of this ContribPower.  # noqa: E501
        :type: str
        """

        self._when = when

    @property
    def contributors(self):
        """Gets the contributors of this ContribPower.  # noqa: E501


        :return: The contributors of this ContribPower.  # noqa: E501
        :rtype: list[ContribPowerDevice]
        """
        return self._contributors

    @contributors.setter
    def contributors(self, contributors):
        """Sets the contributors of this ContribPower.


        :param contributors: The contributors of this ContribPower.  # noqa: E501
        :type: list[ContribPowerDevice]
        """
        if self.local_vars_configuration.client_side_validation and contributors is None:  # noqa: E501
            raise ValueError("Invalid value for `contributors`, must not be `None`")  # noqa: E501

        self._contributors = contributors

    @property
    def modes(self):
        """Gets the modes of this ContribPower.  # noqa: E501


        :return: The modes of this ContribPower.  # noqa: E501
        :rtype: list[int]
        """
        return self._modes

    @modes.setter
    def modes(self, modes):
        """Sets the modes of this ContribPower.


        :param modes: The modes of this ContribPower.  # noqa: E501
        :type: list[int]
        """

        self._modes = modes

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContribPower):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ContribPower):
            return True

        return self.to_dict() != other.to_dict()
