/*
 * PowerMeter API
 * API
 *
 * The version of the OpenAPI document: 2021.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.client.model.HeatsinkVersion;

/**
 * Heatsink
 */

public class Heatsink {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCR = "descr";
  @SerializedName(SERIALIZED_NAME_DESCR)
  private String descr;

  public static final String SERIALIZED_NAME_EDITABLE = "editable";
  @SerializedName(SERIALIZED_NAME_EDITABLE)
  private Boolean editable;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private HeatsinkVersion version;

  public static final String SERIALIZED_NAME_CURRENT_VERSION = "current_version";
  @SerializedName(SERIALIZED_NAME_CURRENT_VERSION)
  private String currentVersion;

  public static final String SERIALIZED_NAME_WIDTH = "width";
  @SerializedName(SERIALIZED_NAME_WIDTH)
  private BigDecimal width;

  public static final String SERIALIZED_NAME_HEIGHT = "height";
  @SerializedName(SERIALIZED_NAME_HEIGHT)
  private BigDecimal height;

  public static final String SERIALIZED_NAME_THICKNESS = "thickness";
  @SerializedName(SERIALIZED_NAME_THICKNESS)
  private BigDecimal thickness;

  public static final String SERIALIZED_NAME_R_CONVEC = "r_convec";
  @SerializedName(SERIALIZED_NAME_R_CONVEC)
  private BigDecimal rConvec;

  public static final String SERIALIZED_NAME_C_CONVEC = "c_convec";
  @SerializedName(SERIALIZED_NAME_C_CONVEC)
  private BigDecimal cConvec;

  public static final String SERIALIZED_NAME_CONDUCTIVITY = "conductivity";
  @SerializedName(SERIALIZED_NAME_CONDUCTIVITY)
  private BigDecimal conductivity;

  public static final String SERIALIZED_NAME_HEATCAPACITY = "heatcapacity";
  @SerializedName(SERIALIZED_NAME_HEATCAPACITY)
  private BigDecimal heatcapacity;


   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getId() {
    return id;
  }




   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }




   /**
   * Get descr
   * @return descr
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescr() {
    return descr;
  }




   /**
   * Get editable
   * @return editable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getEditable() {
    return editable;
  }




  public Heatsink version(HeatsinkVersion version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public HeatsinkVersion getVersion() {
    return version;
  }


  public void setVersion(HeatsinkVersion version) {
    this.version = version;
  }


   /**
   * Get currentVersion
   * @return currentVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCurrentVersion() {
    return currentVersion;
  }




  public Heatsink width(BigDecimal width) {
    
    this.width = width;
    return this;
  }

   /**
   * Get width
   * @return width
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getWidth() {
    return width;
  }


  public void setWidth(BigDecimal width) {
    this.width = width;
  }


  public Heatsink height(BigDecimal height) {
    
    this.height = height;
    return this;
  }

   /**
   * Get height
   * @return height
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getHeight() {
    return height;
  }


  public void setHeight(BigDecimal height) {
    this.height = height;
  }


  public Heatsink thickness(BigDecimal thickness) {
    
    this.thickness = thickness;
    return this;
  }

   /**
   * Get thickness
   * @return thickness
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getThickness() {
    return thickness;
  }


  public void setThickness(BigDecimal thickness) {
    this.thickness = thickness;
  }


  public Heatsink rConvec(BigDecimal rConvec) {
    
    this.rConvec = rConvec;
    return this;
  }

   /**
   * Get rConvec
   * @return rConvec
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getrConvec() {
    return rConvec;
  }


  public void setrConvec(BigDecimal rConvec) {
    this.rConvec = rConvec;
  }


  public Heatsink cConvec(BigDecimal cConvec) {
    
    this.cConvec = cConvec;
    return this;
  }

   /**
   * Get cConvec
   * @return cConvec
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getcConvec() {
    return cConvec;
  }


  public void setcConvec(BigDecimal cConvec) {
    this.cConvec = cConvec;
  }


  public Heatsink conductivity(BigDecimal conductivity) {
    
    this.conductivity = conductivity;
    return this;
  }

   /**
   * Get conductivity
   * @return conductivity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getConductivity() {
    return conductivity;
  }


  public void setConductivity(BigDecimal conductivity) {
    this.conductivity = conductivity;
  }


  public Heatsink heatcapacity(BigDecimal heatcapacity) {
    
    this.heatcapacity = heatcapacity;
    return this;
  }

   /**
   * Get heatcapacity
   * @return heatcapacity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BigDecimal getHeatcapacity() {
    return heatcapacity;
  }


  public void setHeatcapacity(BigDecimal heatcapacity) {
    this.heatcapacity = heatcapacity;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Heatsink heatsink = (Heatsink) o;
    return Objects.equals(this.id, heatsink.id) &&
        Objects.equals(this.name, heatsink.name) &&
        Objects.equals(this.descr, heatsink.descr) &&
        Objects.equals(this.editable, heatsink.editable) &&
        Objects.equals(this.version, heatsink.version) &&
        Objects.equals(this.currentVersion, heatsink.currentVersion) &&
        Objects.equals(this.width, heatsink.width) &&
        Objects.equals(this.height, heatsink.height) &&
        Objects.equals(this.thickness, heatsink.thickness) &&
        Objects.equals(this.rConvec, heatsink.rConvec) &&
        Objects.equals(this.cConvec, heatsink.cConvec) &&
        Objects.equals(this.conductivity, heatsink.conductivity) &&
        Objects.equals(this.heatcapacity, heatsink.heatcapacity);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, descr, editable, version, currentVersion, width, height, thickness, rConvec, cConvec, conductivity, heatcapacity);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Heatsink {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    descr: ").append(toIndentedString(descr)).append("\n");
    sb.append("    editable: ").append(toIndentedString(editable)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    currentVersion: ").append(toIndentedString(currentVersion)).append("\n");
    sb.append("    width: ").append(toIndentedString(width)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    thickness: ").append(toIndentedString(thickness)).append("\n");
    sb.append("    rConvec: ").append(toIndentedString(rConvec)).append("\n");
    sb.append("    cConvec: ").append(toIndentedString(cConvec)).append("\n");
    sb.append("    conductivity: ").append(toIndentedString(conductivity)).append("\n");
    sb.append("    heatcapacity: ").append(toIndentedString(heatcapacity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

