/*
 * PowerMeter API
 * API
 *
 * The version of the OpenAPI document: 2021.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * InstanceSupply
 */

public class InstanceSupply {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_DESIGN_SUPPLY = "design_supply";
  @SerializedName(SERIALIZED_NAME_DESIGN_SUPPLY)
  private Integer designSupply;

  public static final String SERIALIZED_NAME_DESIGN_SUPPLY_NAME = "design_supply_name";
  @SerializedName(SERIALIZED_NAME_DESIGN_SUPPLY_NAME)
  private String designSupplyName;

  public static final String SERIALIZED_NAME_MASTER_SUPPLY = "master_supply";
  @SerializedName(SERIALIZED_NAME_MASTER_SUPPLY)
  private Integer masterSupply;

  public static final String SERIALIZED_NAME_MASTER_SUPPLY_NAME = "master_supply_name";
  @SerializedName(SERIALIZED_NAME_MASTER_SUPPLY_NAME)
  private String masterSupplyName;


   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getId() {
    return id;
  }




  public InstanceSupply designSupply(Integer designSupply) {
    
    this.designSupply = designSupply;
    return this;
  }

   /**
   * Get designSupply
   * @return designSupply
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getDesignSupply() {
    return designSupply;
  }


  public void setDesignSupply(Integer designSupply) {
    this.designSupply = designSupply;
  }


   /**
   * Get designSupplyName
   * @return designSupplyName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDesignSupplyName() {
    return designSupplyName;
  }




  public InstanceSupply masterSupply(Integer masterSupply) {
    
    this.masterSupply = masterSupply;
    return this;
  }

   /**
   * Get masterSupply
   * @return masterSupply
  **/
  @ApiModelProperty(required = true, value = "")

  public Integer getMasterSupply() {
    return masterSupply;
  }


  public void setMasterSupply(Integer masterSupply) {
    this.masterSupply = masterSupply;
  }


   /**
   * Get masterSupplyName
   * @return masterSupplyName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMasterSupplyName() {
    return masterSupplyName;
  }




  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstanceSupply instanceSupply = (InstanceSupply) o;
    return Objects.equals(this.id, instanceSupply.id) &&
        Objects.equals(this.designSupply, instanceSupply.designSupply) &&
        Objects.equals(this.designSupplyName, instanceSupply.designSupplyName) &&
        Objects.equals(this.masterSupply, instanceSupply.masterSupply) &&
        Objects.equals(this.masterSupplyName, instanceSupply.masterSupplyName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, designSupply, designSupplyName, masterSupply, masterSupplyName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstanceSupply {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    designSupply: ").append(toIndentedString(designSupply)).append("\n");
    sb.append("    designSupplyName: ").append(toIndentedString(designSupplyName)).append("\n");
    sb.append("    masterSupply: ").append(toIndentedString(masterSupply)).append("\n");
    sb.append("    masterSupplyName: ").append(toIndentedString(masterSupplyName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

