/*
 * PowerMeter API
 * API
 *
 * The version of the OpenAPI document: 2021.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;

/**
 * PinCap
 */

public class PinCap {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private Integer id;

  public static final String SERIALIZED_NAME_PROCESS = "process";
  @SerializedName(SERIALIZED_NAME_PROCESS)
  private String process;

  public static final String SERIALIZED_NAME_RC = "rc";
  @SerializedName(SERIALIZED_NAME_RC)
  private String rc;

  public static final String SERIALIZED_NAME_VOLTAGE = "voltage";
  @SerializedName(SERIALIZED_NAME_VOLTAGE)
  private BigDecimal voltage;

  public static final String SERIALIZED_NAME_TEMPERATURE = "temperature";
  @SerializedName(SERIALIZED_NAME_TEMPERATURE)
  private BigDecimal temperature;

  public static final String SERIALIZED_NAME_RISE_CAPACITANCE = "rise_capacitance";
  @SerializedName(SERIALIZED_NAME_RISE_CAPACITANCE)
  private BigDecimal riseCapacitance;

  public static final String SERIALIZED_NAME_FALL_CAPACITANCE = "fall_capacitance";
  @SerializedName(SERIALIZED_NAME_FALL_CAPACITANCE)
  private BigDecimal fallCapacitance;


   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getId() {
    return id;
  }




  public PinCap process(String process) {
    
    this.process = process;
    return this;
  }

   /**
   * Get process
   * @return process
  **/
  @ApiModelProperty(required = true, value = "")

  public String getProcess() {
    return process;
  }


  public void setProcess(String process) {
    this.process = process;
  }


  public PinCap rc(String rc) {
    
    this.rc = rc;
    return this;
  }

   /**
   * Get rc
   * @return rc
  **/
  @ApiModelProperty(required = true, value = "")

  public String getRc() {
    return rc;
  }


  public void setRc(String rc) {
    this.rc = rc;
  }


  public PinCap voltage(BigDecimal voltage) {
    
    this.voltage = voltage;
    return this;
  }

   /**
   * Get voltage
   * @return voltage
  **/
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getVoltage() {
    return voltage;
  }


  public void setVoltage(BigDecimal voltage) {
    this.voltage = voltage;
  }


  public PinCap temperature(BigDecimal temperature) {
    
    this.temperature = temperature;
    return this;
  }

   /**
   * Get temperature
   * @return temperature
  **/
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getTemperature() {
    return temperature;
  }


  public void setTemperature(BigDecimal temperature) {
    this.temperature = temperature;
  }


  public PinCap riseCapacitance(BigDecimal riseCapacitance) {
    
    this.riseCapacitance = riseCapacitance;
    return this;
  }

   /**
   * Get riseCapacitance
   * @return riseCapacitance
  **/
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getRiseCapacitance() {
    return riseCapacitance;
  }


  public void setRiseCapacitance(BigDecimal riseCapacitance) {
    this.riseCapacitance = riseCapacitance;
  }


  public PinCap fallCapacitance(BigDecimal fallCapacitance) {
    
    this.fallCapacitance = fallCapacitance;
    return this;
  }

   /**
   * Get fallCapacitance
   * @return fallCapacitance
  **/
  @ApiModelProperty(required = true, value = "")

  public BigDecimal getFallCapacitance() {
    return fallCapacitance;
  }


  public void setFallCapacitance(BigDecimal fallCapacitance) {
    this.fallCapacitance = fallCapacitance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PinCap pinCap = (PinCap) o;
    return Objects.equals(this.id, pinCap.id) &&
        Objects.equals(this.process, pinCap.process) &&
        Objects.equals(this.rc, pinCap.rc) &&
        Objects.equals(this.voltage, pinCap.voltage) &&
        Objects.equals(this.temperature, pinCap.temperature) &&
        Objects.equals(this.riseCapacitance, pinCap.riseCapacitance) &&
        Objects.equals(this.fallCapacitance, pinCap.fallCapacitance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, process, rc, voltage, temperature, riseCapacitance, fallCapacitance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PinCap {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    process: ").append(toIndentedString(process)).append("\n");
    sb.append("    rc: ").append(toIndentedString(rc)).append("\n");
    sb.append("    voltage: ").append(toIndentedString(voltage)).append("\n");
    sb.append("    temperature: ").append(toIndentedString(temperature)).append("\n");
    sb.append("    riseCapacitance: ").append(toIndentedString(riseCapacitance)).append("\n");
    sb.append("    fallCapacitance: ").append(toIndentedString(fallCapacitance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

