/*
 * PowerMeter API
 * API
 *
 * The version of the OpenAPI document: 2021.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ComputedContributorPower1
 */
public class ComputedContributorPower1Test {
    private final ComputedContributorPower1 model = new ComputedContributorPower1();

    /**
     * Model tests for ComputedContributorPower1
     */
    @Test
    public void testComputedContributorPower1() {
        // TODO: test ComputedContributorPower1
    }

    /**
     * Test the property 'p'
     */
    @Test
    public void pTest() {
        // TODO: test p
    }

    /**
     * Test the property 'v'
     */
    @Test
    public void vTest() {
        // TODO: test v
    }

    /**
     * Test the property 't'
     */
    @Test
    public void tTest() {
        // TODO: test t
    }

    /**
     * Test the property 'power'
     */
    @Test
    public void powerTest() {
        // TODO: test power
    }

}
