/*
 * PowerMeter API
 * API
 *
 * The version of the OpenAPI document: 2021.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InstanceModeUtilization
 */
public class InstanceModeUtilizationTest {
    private final InstanceModeUtilization model = new InstanceModeUtilization();

    /**
     * Model tests for InstanceModeUtilization
     */
    @Test
    public void testInstanceModeUtilization() {
        // TODO: test InstanceModeUtilization
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'mastermode'
     */
    @Test
    public void mastermodeTest() {
        // TODO: test mastermode
    }

    /**
     * Test the property 'mastermodeName'
     */
    @Test
    public void mastermodeNameTest() {
        // TODO: test mastermodeName
    }

    /**
     * Test the property 'utilization'
     */
    @Test
    public void utilizationTest() {
        // TODO: test utilization
    }

}
