/*
 * PowerMeter API
 * API
 *
 * The version of the OpenAPI document: 2021.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PackageSupplyInst
 */
public class PackageSupplyInstTest {
    private final PackageSupplyInst model = new PackageSupplyInst();

    /**
     * Model tests for PackageSupplyInst
     */
    @Test
    public void testPackageSupplyInst() {
        // TODO: test PackageSupplyInst
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'container'
     */
    @Test
    public void containerTest() {
        // TODO: test container
    }

    /**
     * Test the property 'master'
     */
    @Test
    public void masterTest() {
        // TODO: test master
    }

    /**
     * Test the property 'color'
     */
    @Test
    public void colorTest() {
        // TODO: test color
    }

    /**
     * Test the property 'connectionColor'
     */
    @Test
    public void connectionColorTest() {
        // TODO: test connectionColor
    }

    /**
     * Test the property 'masterName'
     */
    @Test
    public void masterNameTest() {
        // TODO: test masterName
    }

    /**
     * Test the property 'hierName'
     */
    @Test
    public void hierNameTest() {
        // TODO: test hierName
    }

    /**
     * Test the property 'connectedTo'
     */
    @Test
    public void connectedToTest() {
        // TODO: test connectedTo
    }

    /**
     * Test the property 'connectedToType'
     */
    @Test
    public void connectedToTypeTest() {
        // TODO: test connectedToType
    }

}
