/*
 * PowerMeter API
 * API
 *
 * The version of the OpenAPI document: 2021.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.DesignInstance;
import org.openapitools.client.model.PCBInstance;
import org.openapitools.client.model.PackageInstance;
import org.openapitools.client.model.VRInstance;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ScenarioHierarchy
 */
public class ScenarioHierarchyTest {
    private final ScenarioHierarchy model = new ScenarioHierarchy();

    /**
     * Model tests for ScenarioHierarchy
     */
    @Test
    public void testScenarioHierarchy() {
        // TODO: test ScenarioHierarchy
    }

    /**
     * Test the property 'pcb'
     */
    @Test
    public void pcbTest() {
        // TODO: test pcb
    }

    /**
     * Test the property 'vr'
     */
    @Test
    public void vrTest() {
        // TODO: test vr
    }

    /**
     * Test the property '_package'
     */
    @Test
    public void _packageTest() {
        // TODO: test _package
    }

    /**
     * Test the property 'design'
     */
    @Test
    public void designTest() {
        // TODO: test design
    }

}
