/*
 * PowerMeter API
 * API
 *
 * The version of the OpenAPI document: 2021.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TechnologyMaster
 */
public class TechnologyMasterTest {
    private final TechnologyMaster model = new TechnologyMaster();

    /**
     * Model tests for TechnologyMaster
     */
    @Test
    public void testTechnologyMaster() {
        // TODO: test TechnologyMaster
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'node'
     */
    @Test
    public void nodeTest() {
        // TODO: test node
    }

    /**
     * Test the property 'latestCommit'
     */
    @Test
    public void latestCommitTest() {
        // TODO: test latestCommit
    }

    /**
     * Test the property 'currentVersion'
     */
    @Test
    public void currentVersionTest() {
        // TODO: test currentVersion
    }

    /**
     * Test the property 'latestCommitVersion'
     */
    @Test
    public void latestCommitVersionTest() {
        // TODO: test latestCommitVersion
    }

    /**
     * Test the property 'latestCommitTimestamp'
     */
    @Test
    public void latestCommitTimestampTest() {
        // TODO: test latestCommitTimestamp
    }

}
